import monstera from '../assets/monstera.jpg'

export const plantList = [
	{
		name: 'monstera',
		category: 'classic',
		id: '1ed',
        water:2,
        light:3,
        isBestSale : true,
		cover: monstera,
		price:20,
		

	},
	{
		name: 'ficus lyrata',
		category: 'classic',
		id: '2ab',
        water:3,
        light:1,
        isBestSale : true,
		cover: monstera,
		price:25,
	},
	{
		name: 'silver pothos',
		category: 'classic',
		id: '3sd',
        water:1,
        light:2,
        isBestSale : true,
		cover: monstera,
		price:30,
	},
	{
		name: 'yucca',
		category: 'classic',
		id: '4kk',
        water:3,
        light:1,
        isBestSale : false,
        isSpecialOffer: true,
		cover: monstera,
		price:45,
	},
	{
		name: 'olive tree',
		category: 'exterior',
		id: '5pl',
        water:3,
        light:1,
        isBestSale : true,
		cover: monstera,
		price:10,
	},
	{
		name: 'geranium',
		category: 'exterior',
		id: '6uo',
        water:2,
        light:1,
        isBestSale : false,
		cover: monstera,
		price:15,
	},
	{
		name: 'basil',
		category: 'exterior',
		id: '7ie',
        water:2,
        light:2,
        isBestSale : true,
        isSpecialOffer: true,
		cover: monstera,
		price:30,
	},
	{
		name: 'aloe',
		category: 'succulent',
		id: '8fp',
        water:2,
        light:1,
        isBestSale : false,
        isSpecialOffer: true,
		cover: monstera,
		price:15,
	},
	{
		name: 'succulent',
		category: 'succulent',
		id: '9vn',
        water:3,
        light:2,
        isBestSale : false,
		cover: monstera,
		price:50,
	}
]